version: "3.8"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

services:
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8083:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    ports:
      - 8084:8081
    volumes:
      - shared-workspace:/opt/workspace
      - ../synthea/output_json_bundles:/home/jovyan/work/synthea
    depends_on:
      - spark-master

  jupyter-pathling:
    container_name: jupyter-pathling
    image: jupyter-pathling
    ports: 
      - 4040:4040
      - 8888:8888
    volumes:
      - ./volume:/home/jovyan/work
      - ../synthea/output_json_bundles:/home/jovyan/work/synthea
